# Generated by Django 6.0.4 on 2026-05-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_car_image_carimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='address',
            field=models.CharField(default='Москва, ул. Тверская, 1', max_length=255, verbose_name='Адрес осмотра'),
        ),
    ]
