# Generated by Django 6.0.4 on 2026-05-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_car_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='city',
            field=models.CharField(default='Москва', max_length=100, verbose_name='Город'),
        ),
    ]
